name = "jobstream-scanner-worker"
main = "src/worker/index.ts"
compatibility_date = "2024-01-01"

[vars]
JOBTECH_API_URL = "https://jobstream.api.jobtechdev.se/stream"

[[kv_namespaces]]
binding = "JOB_STORE"
id = "your-kv-namespace-id"

[triggers]
crons = ["*/5 * * * *"] 